#!/usr/bin/env python
#
# wxCSV.py
#
# A first pass at downloading the current and forecast weather 
# and sending it in csv format as an output.
#
# Seth McNeill
# 2013 October 21

import sys
from urllib2 import urlopen
# need to have import try/excepts here
from lxml import etree 
import ForeWx_api as ForeSupermod # generated by generateDS
import ForeWx_proc # generated by generateDS
import curWx_api as CurSupermod # generated by generateDS
import curWx_proc # generated by generateDS

curURL = 'http://w1.weather.gov/xml/current_obs/KLNK.xml'
forecastURL = 'http://forecast.weather.gov/MapClick.php?lat=40.80686&lon=-96.68168&FcstType=digitalDWML'

def processForecast(inXML, N):
  rootObj = ForeSupermod.parseString(inXML, True)
  print "----------------------------------------------"
  print "Forecast Length (hrs): " + str(len(rootObj.data[0].parameters[0].temperature[0].value))
  print "Date: " + rootObj.head.product.creation_date.get_valueOf_()
  print "Location: " + rootObj.data[0].location[0].city.get_valueOf_()
  print "Single prediction test"
  print "Time: " + rootObj.data[0].time_layout[0].start_valid_time[0].get_valueOf_(),
  print "to " + str(rootObj.data[0].time_layout[0].end_valid_time[0])
  for t in rootObj.data[0].parameters[0].temperature:
    print "Temp type " + t.get_type(),
    print t.value[0].get_valueOf_()
  print "precipitation probability: " + rootObj.data[0].parameters[0].probability_of_precipitation[0].value[0].get_valueOf_()
  for w in rootObj.data[0].parameters[0].wind_speed:
    print "wind " + w.get_type() + ': ' + w.value[0].get_valueOf_()
  for d in rootObj.data[0].parameters[0].direction:
    print "direction of " + d.get_type() + ": " + d.value[0].get_valueOf_()

def processCurrent(inXML):
  rootObj = CurSupermod.parseString(inXML, True)
  print "Current Observation"
  print "Station ID: " + rootObj.station_id
  print "Observation Time: " + rootObj.observation_time_rfc822
  print "Current Temp: " + str(rootObj.temp_f) + " F"
  print "Rel Humidity: " + str(rootObj.relative_humidity) + "%"
  print "Wind: " + str(rootObj.wind_mph) + " mph at " + str(rootObj.wind_degrees) + " degrees gusting " + str(rootObj.wind_gust_mph) + " mph"
  print "Pressure: " + str(rootObj.pressure_in) + " in or " + str(rootObj.pressure_mb) + " mb"
  print "Current DewPoint: " + str(rootObj.dewpoint_f) + " F"
  print "Windchill: " + str(rootObj.windchill_f) + " F"
  print "Visibility: " + str(rootObj.visibility_mi) + " mi"
  


USAGE_MSG = """\
   python wxCSV.py
"""

def usage():
  print USAGE_MSG
  sys.exit(1)

def main():
  args = sys.argv[1:]
  if(len(args) != 0):
    usage()
  curXML = urlopen(curURL).read()
  processCurrent(curXML)
  forecastXML = urlopen(forecastURL).read()
  processForecast(forecastXML, 5) 

if __name__ == '__main__':
  main()


